# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_auto_20180312_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('partyType', models.IntegerField(default=0)),
                ('partyId', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('others', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
